<a href="https://colab.research.google.com/github/zzhenxi/study-NLP-with-PyTorch/blob/main/chapter_1_pytorch_%EA%B8%B0%EB%B3%B8_%EA%B0%9C%EB%85%90_%ED%95%99%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# 헬퍼함수
def describe(x):
  print("타입: {}".format(x.type()))
  print("크기: {}".format(x.shape))
  print("값: \n{}".format(x))

In [4]:
import torch 
describe(torch.Tensor(2,3)) # 랜덤한 tenesor를 만듦.

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[-5.0576e-04,  3.0667e-41,  3.7835e-44],
        [ 0.0000e+00,         nan,  3.0667e-41]])


In [ ]:
import torch 
describe(torch.rand(2, 3)) # 균등 분포
describe(torch.rand(2, 3)) # 표준 정규 분포 -> 평균이 0이고, 분산이 1인 정규 분포

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.7906, 0.4836, 0.1392],
        [0.6615, 0.3491, 0.8173]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.5903, 0.0126, 0.0301],
        [0.7590, 0.6536, 0.9903]])


In [ ]:
import torch
describe(torch.zeros(2, 3))
x = torch.ones(2, 3)
describe(x)
x.fill_(5) # 여기서 0->5로 바뀜
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [ ]:
x = torch.Tensor([[1,2,3],
                  [4,5,6]]) # python list로 텐서 만들기
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
import torch
import numpy as np
npy = np.random.rand(2,3)
describe(torch.from_numpy(npy))

타입: torch.DoubleTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.9692, 0.7251, 0.6429],
        [0.8660, 0.1730, 0.2053]], dtype=torch.float64)


In [ ]:
x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
x = x.long()
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[1, 2, 3],
        [4, 5, 6]])


파이토치 코드를 디버길 할때는 텐서 크기를 꼭 조사하기!   
* .size()
* .shape

In [ ]:
import torch
x = torch.arange(6)
describe(x)

타입: torch.LongTensor
크기: torch.Size([6])
값: 
tensor([0, 1, 2, 3, 4, 5])


In [ ]:
x = x.view(2,3) # 2,2같은 숫자를 넣어주면 맞지않은 차원이라는 에러가 뜸. 
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [ ]:
describe(torch.sum(x, dim=0)) # 2d 텐서는 행을 차원0, 열을 차원1로 표현

타입: torch.LongTensor
크기: torch.Size([3])
값: 
tensor([3, 5, 7])


In [ ]:
describe(torch.sum(x,dim=1)) # 2d 텐서는 행을 차원0, 열을 차원1로 표현

타입: torch.LongTensor
크기: torch.Size([2])
값: 
tensor([ 3, 12])


In [ ]:
describe(torch.transpose(x, 0, 1))

타입: torch.LongTensor
크기: torch.Size([3, 2])
값: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [ ]:
import torch
x = torch.arange(6).view(2,3)
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [ ]:
describe(x[1, 2]) # 0번째 행에서 0, 1번째 열 뽑기

타입: torch.LongTensor
크기: torch.Size([])
값: 
5


In [ ]:
describe(x[0, 1]) # 0번째 행에서 1번째 열 뽑기 

타입: torch.LongTensor
크기: torch.Size([])
값: 
1


In [ ]:
indices = torch.LongTensor([0, 2])
describe(torch.index_select(x, dim=1, index=indices)) # index는 vector여야 한다.

타입: torch.LongTensor
크기: torch.Size([2, 2])
값: 
tensor([[0, 2],
        [3, 5]])


In [ ]:
indices = torch.LongTensor([0, 0])
describe(torch.index_select(x, dim=0, index=indices)) # index는 vector여야 한다.

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [0, 1, 2]])


In [ ]:
row_indices = torch.arange(2).long() #0번, 그리고 1번
col_indices = torch.LongTensor([0,1])
describe(x[row_indices, col_indices])

타입: torch.LongTensor
크기: torch.Size([2])
값: 
tensor([0, 4])


In [ ]:
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
row_indices

tensor([0, 1])

In [ ]:
import torch
x = torch.arange(6).view(2,3)
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [ ]:
describe(torch.cat([x, x], dim=0)) # 행을 기준으로 cat

타입: torch.LongTensor
크기: torch.Size([4, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


In [ ]:
describe(torch.cat([x, x], dim=1)) # 열을 기준으로 cat

타입: torch.LongTensor
크기: torch.Size([2, 6])
값: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [ ]:
describe(torch.stack([x, x])) # 그냥 통째로 쌓임

타입: torch.LongTensor
크기: torch.Size([2, 2, 3])
값: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


In [ ]:
x2 = torch.ones(3,2)
x2[:, 1] += 1 # 1번째 열에만 1이 다 더해짐
describe(x2) 

타입: torch.FloatTensor
크기: torch.Size([3, 2])
값: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])


In [ ]:
x1 = torch.arange(6).view(2,3).float() # .float()이걸 써야 오류가 안뜬다. 왜지?
x2 = torch.ones(3,2)
x2[:, 1] += 1 # 1번째 열에만 1이 다 더해짐
describe(torch.mm(x1, x2))

타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: 
tensor([[ 3.,  6.],
        [12., 24.]])


In [ ]:
import torch
x = torch.ones(2, 2, requires_grad=True)
describe(x)
print(x.grad is None)

타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True


In [ ]:
y = (x+2) * (x+5) +3
describe(y)
print(x.grad is None)

타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)
True


In [ ]:
z = y.mean()
describe(z)
z.backward()
print(x.grad is None)

타입: torch.FloatTensor
크기: torch.Size([])
값: 
21.0
False


In [ ]:
x.grad # 값이 변했다?! 

tensor([[2.2500, 2.2500],
        [2.2500, 2.2500]])

In [ ]:
import torch
print(torch.cuda.is_available())

True


In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
print(device)

cuda


In [ ]:
x = torch.rand(3,3).to(device)
describe(x)

타입: torch.cuda.FloatTensor
크기: torch.Size([3, 3])
값: 
tensor([[0.0232, 0.4516, 0.2702],
        [0.2934, 0.6457, 0.6241],
        [0.6932, 0.3942, 0.5636]], device='cuda:0')


In [ ]:
y = torch.rand(3,3)
x+y

RuntimeError: ignored

In [ ]:
cpu_Device = torch.device("cpu")

In [ ]:
y = y.to(cpu_Device) 
x = x.to(cpu_Device)
x+y

tensor([[0.2088, 1.0796, 0.2830],
        [0.8999, 0.9661, 0.9941],
        [1.3148, 0.9681, 1.5298]])

gpu로 메모리를 넣고 꺼내는 작업은 비용이 많이 든다고 한다! 되도록 병렬연산은 gpu로 수행하고, 최종결과만 cpu로 전송하는 방식이 좋음

In [ ]:
# 1. 2d 텐서를 만들고 차원 0 위치에 크기가 1인 차원을 추가하세요 
a = torch.Tensor(2,3)

In [ ]:
describe(a)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1.0580e-31, 3.0676e-41, 1.5975e-43],
        [1.3873e-43, 1.4574e-43, 6.4460e-44]])


In [ ]:
a = a.unsqueeze(0)

In [ ]:
describe(a)

타입: torch.FloatTensor
크기: torch.Size([1, 2, 3])
값: 
tensor([[[1.0580e-31, 3.0676e-41, 1.5975e-43],
         [1.3873e-43, 1.4574e-43, 6.4460e-44]]])


In [ ]:
# 2.  이전 텐서에 추가한 차원을 삭제하세요
a = a.squeeze()

In [ ]:
describe(a)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1.0580e-31, 3.0676e-41, 1.5975e-43],
        [1.3873e-43, 1.4574e-43, 6.4460e-44]])


squeeze와 unsqueeze를 쓰는 이유는 무엇일까?    
의미없는 텐서 삭제를 위해?

In [13]:
# 3. 범위가 [3,7) -> 3이상 7미만이고 크기가 5*3인 랜덤한 텐서를 만드세요
3 + (torch.rand(5, 3) * 4) # 더해주거나 곱해주는 연산은 모든 텐서에 다 적용된다. 

tensor([[4.0262, 4.0104, 5.4886],
        [6.7823, 4.0009, 3.1575],
        [3.7579, 4.5594, 3.0783],
        [6.2500, 6.3536, 3.7618],
        [6.3837, 5.4473, 3.7635]])

In [21]:
# 4. 정규 분포(평균=0, 표준편차=1)를 사용해 텐서를 만드세요.
torch.randn(3)

tensor([ 0.3489,  0.4372, -0.1147])

In [5]:
# 5. 텐서 torch.Tensor([1, 1, 1, 0, 1])에서 0이 아닌 원소의 인덱스를 추출하세요.
a = torch.Tensor([1, 1, 1, 0, 1])

In [24]:
a[a>0]

tensor([1., 1., 1., 1.])

In [6]:
torch.nonzero(a)

tensor([[0],
        [1],
        [2],
        [4]])

In [20]:
# 6. 크기가  (3,1)인 랜덤한 텐서를 만들고 네벌을 복사해 쌓으세요 
a = torch.rand(3, 1)
a

tensor([[0.2745],
        [0.7271],
        [0.0235]])

In [21]:
a.expand(3,4) # 특정 텐서를 반복하여 생성하지만, 개수가 1인 텐서에 대해서만 가능하다. 그리고 차원이 맞아야 한다. 

tensor([[0.2745, 0.2745, 0.2745, 0.2745],
        [0.7271, 0.7271, 0.7271, 0.7271],
        [0.0235, 0.0235, 0.0235, 0.0235]])

반환된 값은 뷰텐서로 늘어난 영역이 새로운 메모리 공간을 점유하지 않는다. 

In [24]:
a.expand(-1,4) # 차원이 어차피 맞아 떨어져야 함(3)으로 -1로 표기해주면 굳이 숫자를 맞춰줄 필요 없다. 

tensor([[0.2745, 0.2745, 0.2745, 0.2745],
        [0.7271, 0.7271, 0.7271, 0.7271],
        [0.0235, 0.0235, 0.0235, 0.0235]])

In [23]:
describe(a)

타입: torch.FloatTensor
크기: torch.Size([3, 1])
값: 
tensor([[0.2745],
        [0.7271],
        [0.0235]])


In [29]:
# 7. 2차원 행렬 두개의 배치 행렬 곱셈을 계산하세요. 
a = torch.rand(3,4,5) #batch*n*m
b = torch.rand(3,5,4) #batch*m*n
a = a.bmm(b) 

In [30]:
describe(a) # batch*n*n

타입: torch.FloatTensor
크기: torch.Size([3, 4, 4])
값: 
tensor([[[1.8197, 1.3108, 1.4956, 1.7767],
         [1.1430, 0.7856, 1.3477, 1.5383],
         [1.3133, 1.1403, 1.1662, 0.8591],
         [2.0262, 1.5106, 2.0030, 2.1529]],

        [[1.1064, 1.3024, 0.9350, 0.8459],
         [1.6639, 2.2181, 1.3466, 1.1958],
         [1.2632, 1.6236, 1.0616, 0.9431],
         [1.4502, 2.2091, 1.2497, 1.1473]],

        [[0.7638, 1.1804, 1.1150, 0.7412],
         [1.5764, 1.8134, 1.5252, 1.7257],
         [1.8938, 2.1505, 2.1556, 2.1041],
         [0.8184, 0.7413, 0.9995, 0.9948]]])


In [ ]:
# 8. 3차원 행렬과 2차원 행렬의 배치 행렬 곱셈을 계산하세요.
a = torch.rand(3,4,5) 
b = torch.rand(5,4) 
torch.bmm(a, b.unsqueeze(0).expand(a.size, *b.size()))