<a href="https://colab.research.google.com/github/zzhenxi/study-NLP-with-PyTorch/blob/main/chapter_1_pytorch_%EA%B8%B0%EB%B3%B8_%EA%B0%9C%EB%85%90_%ED%95%99%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
# 헬퍼함수
def describe(x):
  print("타입: {}".format(x.type()))
  print("크기: {}".format(x.shape))
  print("값: \n{}".format(x))

In [ ]:
import torch 
describe(torch.Tensor(2,3)) # 랜덤한 tenesor를 만듦.

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[-4.6446e+23,  3.0686e-41,  3.7835e-44],
        [ 0.0000e+00,         nan,  3.0686e-41]])


In [ ]:
import torch 
describe(torch.rand(2, 3)) # 균등 분포
describe(torch.rand(2, 3)) # 표준 정규 분포 -> 평균이 0이고, 분산이 1인 정규 분포

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.2319, 0.9661, 0.1885],
        [0.2938, 0.5103, 0.0991]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.1082, 0.5044, 0.7547],
        [0.0557, 0.1187, 0.3606]])


In [ ]:
import torch
describe(torch.zeros(2, 3))
x = torch.ones(2, 3)
describe(x)
x.fill_(5) # 여기서 0->5로 바뀜
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [ ]:
x = torch.Tensor([[1,2,3],
                  [4,5,6]]) # python list로 텐서 만들기
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
import torch
import numpy as np
npy = np.random.rand(2,3)
describe(torch.from_numpy(npy))

타입: torch.DoubleTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.0883, 0.4969, 0.3917],
        [0.0239, 0.6479, 0.4952]], dtype=torch.float64)


In [ ]:
x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
x = x.long()
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[1, 2, 3],
        [4, 5, 6]])


파이토치 코드를 디버길 할때는 텐서 크기를 꼭 조사하기!   
* .size()
* .shape

In [ ]:
import torch
x = torch.arange(6)
describe(x)

타입: torch.LongTensor
크기: torch.Size([6])
값: 
tensor([0, 1, 2, 3, 4, 5])


In [ ]:
x = x.view(2,3) # 2,2같은 숫자를 넣어주면 맞지않은 차원이라는 에러가 뜸. 
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [ ]:
describe(torch.sum(x, dim=0)) # 2d 텐서는 행을 차원0, 열을 차원1로 표현

타입: torch.LongTensor
크기: torch.Size([3])
값: 
tensor([3, 5, 7])


In [ ]:
describe(torch.sum(x,dim=1)) # 2d 텐서는 행을 차원0, 열을 차원1로 표현

타입: torch.LongTensor
크기: torch.Size([2])
값: 
tensor([ 3, 12])


In [ ]:
describe(torch.transpose(x, 0, 1))

타입: torch.LongTensor
크기: torch.Size([3, 2])
값: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [2]:
import torch
x = torch.arange(6).view(2,3)
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [30]:
describe(x[1, 2]) # 0번째 행에서 0, 1번째 열 뽑기

타입: torch.LongTensor
크기: torch.Size([])
값: 
5


In [5]:
describe(x[0, 1]) # 0번째 행에서 1번째 열 뽑기 

타입: torch.LongTensor
크기: torch.Size([])
값: 
1


In [28]:
indices = torch.LongTensor([0, 2])
describe(torch.index_select(x, dim=1, index=indices)) # index는 vector여야 한다.

타입: torch.LongTensor
크기: torch.Size([2, 2])
값: 
tensor([[0, 2],
        [3, 5]])


In [29]:
indices = torch.LongTensor([0, 0])
describe(torch.index_select(x, dim=0, index=indices)) # index는 vector여야 한다.

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [0, 1, 2]])


In [34]:
row_indices = torch.arange(2).long() #0번, 그리고 1번
col_indices = torch.LongTensor([0,1])
describe(x[row_indices, col_indices])

타입: torch.LongTensor
크기: torch.Size([2])
값: 
tensor([0, 4])


In [32]:
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [33]:
row_indices

tensor([0, 1])

In [35]:
import torch
x = torch.arange(6).view(2,3)
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [36]:
describe(torch.cat([x, x], dim=0)) # 행을 기준으로 cat

타입: torch.LongTensor
크기: torch.Size([4, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


In [37]:
describe(torch.cat([x, x], dim=1)) # 열을 기준으로 cat

타입: torch.LongTensor
크기: torch.Size([2, 6])
값: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [39]:
describe(torch.stack([x, x])) # 그냥 통째로 쌓임

타입: torch.LongTensor
크기: torch.Size([2, 2, 3])
값: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


In [42]:
import torch 

describe(x1)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [43]:
x2 = torch.ones(3,2)
x2[:, 1] += 1 # 1번째 열에만 1이 다 더해짐
describe(x2) 

타입: torch.FloatTensor
크기: torch.Size([3, 2])
값: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])


In [47]:
x1 = torch.arange(6).view(2,3).float() # .float()이걸 써야 오류가 안뜬다. 왜지?
x2 = torch.ones(3,2)
x2[:, 1] += 1 # 1번째 열에만 1이 다 더해짐
describe(torch.mm(x1, x2))

타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: 
tensor([[ 3.,  6.],
        [12., 24.]])


In [48]:
import torch
x = torch.ones(2, 2, requires_grad=True)
describe(x)
print(x.grad is None)

타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True


In [50]:
y = (x+2) * (x+5) +3
describe(y)
print(x.grad is None)

타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)
True


In [51]:
z = y.mean()
describe(z)
z.backward()
print(x.grad is None)

타입: torch.FloatTensor
크기: torch.Size([])
값: 
21.0
False


In [54]:
x.grad # 값이 변했다?! 

tensor([[2.2500, 2.2500],
        [2.2500, 2.2500]])

In [1]:
import torch
print(torch.cuda.is_available())

True


In [5]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [6]:
print(device)

cuda


In [14]:
x = torch.rand(3,3).to(device)
describe(x)

타입: torch.cuda.FloatTensor
크기: torch.Size([3, 3])
값: 
tensor([[0.9953, 0.8687, 0.7252],
        [0.1378, 0.6275, 0.2449],
        [0.9939, 0.7235, 0.9974]], device='cuda:0')


In [10]:
y = torch.rand(3,3)
x+y

RuntimeError: ignored

In [15]:
cpu_Device = torch.device("cpu")

In [17]:
y = y.to(cpu_Device) 
x = x.to(cpu_Device)
x+y

tensor([[1.2469, 1.3779, 1.3152],
        [0.9809, 1.2794, 0.8206],
        [1.2755, 1.1648, 1.6234]])

gpu로 메모리를 넣고 꺼내는 작업은 비용이 많이 든다고 한다! 되도록 병렬연산은 gpu로 수행하고, 최종결과만 cpu로 전송하는 방식이 좋음