<a href="https://colab.research.google.com/github/zzhenxi/study-NLP-with-PyTorch/blob/main/chapter_1_pytorch_%EA%B8%B0%EB%B3%B8_%EA%B0%9C%EB%85%90_%ED%95%99%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
def describe(x):
  print("타입: {}".format(x.type()))
  print("크기: {}".format(x.shape))
  print("값: \n{}".format(x))

In [2]:
import torch 
describe(torch.Tensor(2,3)) # 랜덤한 tenesor를 만듦.

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[-4.6446e+23,  3.0686e-41,  3.7835e-44],
        [ 0.0000e+00,         nan,  3.0686e-41]])


In [3]:
import torch 
describe(torch.rand(2, 3)) # 균등 분포
describe(torch.rand(2, 3)) # 표준 정규 분포 -> 평균이 0이고, 분산이 1인 정규 분포

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.2319, 0.9661, 0.1885],
        [0.2938, 0.5103, 0.0991]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.1082, 0.5044, 0.7547],
        [0.0557, 0.1187, 0.3606]])


In [4]:
import torch
describe(torch.zeros(2, 3))
x = torch.ones(2, 3)
describe(x)
x.fill_(5) # 여기서 0->5로 바뀜
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [5]:
x = torch.Tensor([[1,2,3],
                  [4,5,6]]) # python list로 텐서 만들기
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [6]:
import torch
import numpy as np
npy = np.random.rand(2,3)
describe(torch.from_numpy(npy))

타입: torch.DoubleTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.0883, 0.4969, 0.3917],
        [0.0239, 0.6479, 0.4952]], dtype=torch.float64)


In [10]:
x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [11]:
x = x.long()
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[1, 2, 3],
        [4, 5, 6]])


파이토치 코드를 디버길 할때는 텐서 크기를 꼭 조사하기!   
* .size()
* .shape

In [13]:
import torch
x = torch.arange(6)
describe(x)

타입: torch.LongTensor
크기: torch.Size([6])
값: 
tensor([0, 1, 2, 3, 4, 5])


In [18]:
x = x.view(2,3) # 2,2같은 숫자를 넣어주면 맞지않은 차원이라는 에러가 뜸. 
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [19]:
describe(torch.sum(x, dim=0)) # 2d 텐서는 행을 차원0, 열을 차원1로 표현

타입: torch.LongTensor
크기: torch.Size([3])
값: 
tensor([3, 5, 7])


In [21]:
describe(torch.sum(x,dim=1)) # 2d 텐서는 행을 차원0, 열을 차원1로 표현

타입: torch.LongTensor
크기: torch.Size([2])
값: 
tensor([ 3, 12])


In [22]:
describe(torch.transpose(x, 0, 1))

타입: torch.LongTensor
크기: torch.Size([3, 2])
값: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])
